version: "3.9"
services:
  db:
    image: postgres:15
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports: ["5432:5432"]

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports: ["10000:10000", "10001:10001", "10002:10002"]
    volumes:
      - ./data:/azdata

  web:
    build: ./backend
    command: >
      sh -c "sleep 5 &&
            python manage.py wait_for_azurite &&
            python manage.py init_azurite &&
            python manage.py list_blobs --upload &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on: [db, azurite]
    environment:
      # DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
      AZURE_STORAGE_CONTAINER: ${AZURE_STORAGE_CONTAINER}
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
      PYTHONIOENCODING: utf-8
      PYTHONUNBUFFERED: 1
    ports: ["8000:8000"]
    volumes:
      - ./backend/code:/code
      - ./data:/data:ro

  django-migrate:
    build: ./backend  # 既存のwebサービスと同じDockerイメージを使用
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"
    depends_on: [db]  # dbのみに依存
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AZURE_DISABLE: "True"  # Azuriteへの接続を無効化
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
      PYTHONIOENCODING: utf-8
    volumes:
      - ./backend/code:/code

  func:
    build: ./functions
    depends_on: [db, azurite]
    environment:
      AzureWebJobsStorage: ${AZURE_CONNECTION_STRING}
      PG_CONN: host=db port=5432 dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}
    ports: ["7071:7071"]

